controller:
  replicas: 3
  env: 
  - name: NV_PLATFORM_INFO
    value: "platform=Kubernetes:GKE"
  nodeSelector:
    node-role.kubernetes.io/nvcontroller: ""
  secret:
    enabled: true
    data:
      userinitcfg.yaml: 
        always_reload: true
        users:
        -
          Fullname: admin
          Password: 
          Role: admin

manager:
  svc:
    type: LoadBalancer

cve:
  scanner:
    replicas: 2
    nodeSelector:
      node-role.kubernetes.io/nvcontroller: ""

resources:
  limits:
    cpu: 400m
    memory: 2792Mi
  requests:
    cpu: 100m
    memory: 2280Mi

containerd:
  enabled: true
  path: /var/run/containerd/containerd.sock
